services:
  mysql:
    image: mysql:8.0
    container_name: mysql8
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_DATABASE=iris
      - MYSQL_USERNAME=iris
      - MYSQL_PASSWORD=irispass
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      interval: 10s
      timeout: 5s
      retries: 5
  indexer:
    build: .
    container_name: iris-indexer
    restart: unless-stopped
    ports:
      - '3001:3000'
    volumes:
      - iris_logs:/app/logs
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - DATABASE_HOST=mysql
      - DATABASE_PORT=3306
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=rootpass
      - DATABASE=iris
      - DATABASE_TYPE=mysql
      - GITHUB_ACCESS_TOKEN=1
      - OPERATION_WEBSOCKET_PORT=8888
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
  iris_logs:
    driver: local
