services:
  mysql:
    env_file: .env
    container_name: mysql
    image: 'mysql:latest'
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${DATABASE}
      - MYSQL_USER=${DATABASE_USERNAME}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - '3306:3306'
    # networks:
    #   - app-network
  indexer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: iris-indexer
    image: iris-indexer
    restart: unless-stopped
    ports:
      - '3001:3001'
    volumes:
      - iris_logs:/app/logs
    depends_on:
      - mysql
    env_file: .env
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
  iris_logs:
    driver: local
