name: Docker only
on:
  push:
    branches:
      - 'master'
env:
  IMAGE_REPOSITORY: asia.gcr.io/develop-430303/iris

jobs:
  docker:
    runs-on: ubuntu-latest
    #needs: ["trivy"]
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/heads/release')
    steps:
      - uses: actions/checkout@v3

      - name: prepare
        id: before_script
        run: |
          #!/bin/bash

          if [[ "$IMAGE_REPOSITORY" == "" ]]; then
            echo "IMAGE_REPOSITORY must be define."
            exit 1
          fi

          BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/})
          IMAGE_TAG=""

          if [[ "${BRANCH_NAME}" == "main" || "${BRANCH_NAME}" == "master" ]]; then
            IMAGE_TAG=main-$(echo ${GITHUB_SHA::7})
          elif [[ "${BRANCH_NAME}" == release-* ]]; then
            IMAGE_TAG=release-$(echo ${GITHUB_SHA::7})
          else
            echo "Docker build only happens in branch 'main' or 'release-*'"
            exit 0
          fi

          echo "::set-output name=BRANCH_NAME::${BRANCH_NAME}"
          echo "::set-output name=IMAGE_URL::${IMAGE_REPOSITORY}:${IMAGE_TAG}"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Gcloud Auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCR_CREDENTIALS }}'

      - name: Setup Gcloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure docker
        run: gcloud auth configure-docker

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-${{ env.SERVICE }}-buildx

      - name: Docker build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ steps.before_script.outputs.IMAGE_URL }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new

      - name: Move Docker cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
